elastic:                                                         
  image: elasticsearch   
  volumes:                                                       
   - /opt/data/esBBB:/var/lib/elasticsearch  
