elastic:                                                         
  image: elasticsearch
  volumes:                                                       
   - /opt/data/esAAA:/var/lib/elasticsearch 
